# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/05_algorithm.ipynb (unless otherwise specified).

__all__ = ['epsilon_greedy']

# Cell
#export
import numpy.random as npr

def epsilon_greedy(epsilon, sample_func, agent_action_func):
    def func(s):
        if epsilon > npr.uniform():
            return sample_func()
        else:
            return agent_action_func(s)
    return func